spring.application.name=monitor-precos

# 1. Porta onde o servidor vai rodar 
server.port=8080

# 2. Habilitar o painel visual do banco H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. Conexão com o banco de dados na memória RAM
spring.datasource.url=jdbc:h2:mem:garimpeirodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 4. Criar as tabelas sozinho
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect